version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: canvas
    versions:
    - 2.7.0
  - dependency-name: gl
    versions:
    - 4.9.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
  - dependency-name: "@types/ramda"
    versions:
    - 0.27.37
    - 0.27.38
    - 0.27.39
    - 0.27.40
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: three
    versions:
    - 0.125.2
    - 0.126.0
    - 0.126.1
    - 0.127.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: typescript
    versions:
    - 3.9.8
    - 3.9.9
  - dependency-name: lint-staged
    versions:
    - 10.5.4
